package schema

// ChatRequest is the POST /api/chat request body.
type ChatRequest struct {
	Message       string `json:"message"`
	SessionID     string `json:"sessionId,omitempty"`
	ChatSessionID string `json:"chat_session_id,omitempty"`
	AnonymousID   string `json:"anonymous_id,omitempty"`
	RequestID     string `json:"requestId,omitempty"`
	Action        string `json:"action,omitempty"`
	ProductURL    string `json:"productUrl,omitempty"`
	ProductName   string `json:"productName,omitempty"`
}

type SuggestionsResponse struct {
	Suggestions []string `json:"suggestions"`
}

type HealthResponse struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Time    string `json:"time"`
}

const (
	SSEEventStatus         = "status"
	SSEEventDelta          = "delta"
	SSEEventSources        = "sources"
	SSEEventDisclaimer     = "disclaimer"
	SSEEventDone           = "done"
	SSEEventError          = "error"
	SSEEventProducts       = "products"
	SSEEventProductsUpdate = "products_update"
	SSEEventDetailItems    = "detail_items"
)

type SSEStatusPayload struct {
	Stage   string `json:"stage"`
	Message string `json:"message"`
}

type SSEDeltaPayload struct {
	Text string `json:"text"`
}

type SourceItem struct {
	Title      string `json:"title"`
	URL        string `json:"url"`
	Site       string `json:"site"`
	ProductURL string `json:"product_url,omitempty"`
}

type SSESourcesPayload struct {
	Items []SourceItem `json:"items"`
}

type SSEDisclaimerPayload struct {
	Text string `json:"text"`
}

type SSEDonePayload struct {
	RequestID string `json:"requestId"`
}

type SSEErrorPayload struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"requestId,omitempty"`
}

type IntentResult struct {
	Intent        string   `json:"intent"`
	NeedsFollowup bool     `json:"needs_followup"`
	MissingSlots  []string `json:"missing_slots"`
	Reason        string   `json:"reason"`
}

type QueryResult struct {
	Queries []string `json:"queries"`
}

type SearchResultItem struct {
	Title       string   `json:"title"`
	URL         string   `json:"url"`
	Site        string   `json:"site"`
	Snippet     string   `json:"snippet"`
	ProductURL  string   `json:"product_url,omitempty"`
	ProductName string   `json:"product_name,omitempty"`
	Tags        []string `json:"tags,omitempty"`
}

type AnswerResult struct {
	Summary string   `json:"summary"`
	Details []string `json:"details"`
	Caution string   `json:"caution,omitempty"`
}

// ProductCard is generated by backend logic rather than by LLM output.
type ProductCard struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	Company    string   `json:"company"`
	Price      string   `json:"price,omitempty"`
	PriceLabel string   `json:"price_label"`
	Tags       []string `json:"tags"`
	URL        string   `json:"url"`
	Platform   string   `json:"platform"`
	Brief      string   `json:"brief"`
}

type SSEProductsPayload struct {
	Items []ProductCard `json:"items"`
}

type SSEProductsUpdatePayload struct {
	Items []ProductCard `json:"items"`
}

type DutyItem struct {
	Name        string `json:"name"`
	Coverage    string `json:"coverage"`
	Description string `json:"description"`
	IsOptional  bool   `json:"is_optional"`
}

type ProductDetail struct {
	ProductName string     `json:"product_name"`
	ProductURL  string     `json:"product_url"`
	Platform    string     `json:"platform"`
	Duties      []DutyItem `json:"duties"`
	CNCharCount int        `json:"cn_char_count"`
	MatchRate   float64    `json:"match_rate"`
}

type SSEDetailItemsPayload struct {
	ProductName string     `json:"product_name"`
	Duties      []DutyItem `json:"duties"`
}
